PILOT-1814: Remove deprecated lineage creation endpoint
PilotDataPlatform/bff-cli pull request #18
Opened 2022-10-17 17:01 UTC by afmam

## Summary

- Remove endpoint for creating lineage via audit-trail service, as this was deprecated. Lineage is now created in Apache Atlas by the metadata-event-handler.

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1814

## Type of Change

- [X] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [X] Yes
- [ ] No

## Test Directions

- File/folder copy request will create lineage without invoking audit-trail service.

2022-10-17 17:26 UTC, QXgu commented on app/api_registry.py
> -    app.include_router(api_lineage.router, prefix=prefix)
I think we should not deprecate this API endpoint

2022-10-17 17:26 UTC, QXgu requested changes

2022-10-17 17:26 UTC, QXgu commented on app/models/lineage_models.py
> -    result: dict = Field({}, example={'message': 'Succeed'})
CLI still calling this API endpoint

2022-10-18 15:49 UTC, QXgu approved these changes

2022-11-24 17:07 UTC, colorzzr commented
updated with cli https://github.com/PilotDataPlatform/cli/pull/9

2022-11-24 18:45 UTC, merged